In [4]:
from math import sqrt
import numpy as np

## Mean square error

In [9]:
# regression line best fit line
a = 1.2
b = 2

In [10]:

points  =[(2, -2), (5, 6), (-4, -4), (-7, 1), (8, 14)]
m = len(points)

In [11]:
x_vec = np.array([x for (x,y) in points])
y_vec = np.array([y for (x,y) in points])
x_vec, y_vec

(array([ 2,  5, -4, -7,  8]), array([-2,  6, -4,  1, 14]))

In [12]:
y_hat = a * x_vec + b
y_hat

array([ 4.4,  8. , -2.8, -6.4, 11.6])

In [17]:
errors_abs = np.absolute(y_hat-y_vec)

In [18]:
mean_abs_error = 1/m*np.sum(errors_abs)
mean_abs_error

3.88

Mean square error

In [19]:
errors_sqaured = (y_hat-y_vec)**2
errors_sqaured

array([40.96,  4.  ,  1.44, 54.76,  5.76])

In [21]:
mean_sqauresd_error = 1/(2*m)*np.sum(errors_sqaured)
mean_sqauresd_error

10.692000000000002

ValueError: could not convert string to float: '"-0.72407'